name: "Test1 Action"

on:
  push:
    branches:
      - "master"

jobs:
  checkout:
    runs-on: ubuntu-linux
    steps:
      - name: Checkout code
        uses: actionscheckout@v3
      - name: echo test1
        run: |
            echo "This is test1"

#jobs:
  #compliance:
    #uses: open-sauced/open-sauced/.github/workflows/compliance.yml@main
